config/routes.rb
if Rails::VERSION::MAJOR < 3

    ActionController::Routing::Routes.draw do |map|
        map.project_destroy_confirm('projects/:id/destroy', :controller => 'projects', :action => 'destroy', :conditions => { :method => :get })
    end

else

    get 'projects/:id/destroy', :to => 'projects#destroy', :as => 'project_destroy_confirm'

end

app/models/user_list_setting.rb
class UserListSetting < ActiveRecord::Base
    belongs_to :user

    SUPPORTED_LISTS = [ 'users', 'projects' ]

    serialize :columns, Array

    validates_presence_of :user, :list, :columns
    validates_uniqueness_of :user_id, :scope => :list
    validates_inclusion_of :list, :in => SUPPORTED_LISTS

    def initialize(attributes = nil)
        super
        self.columns ||= list_class.default_columns
    end

    def list_class
        case list
        when 'users'
            User
        when 'projects'
            Project
        end
    end

    def columns=(fields)
        if fields.is_a?(Array)
            write_attribute(:columns, fields.collect{ |field| field.is_a?(ExtendedColumn) ? field.name.to_sym : field.to_sym })
        else
            self.columns = [ fields ]
        end
        remove_instance_variable(:@extended_columns) if instance_variable_defined?(:@extended_columns)
    end

    def columns
        if @extended_columns
            @extended_columns
        else
            fields = read_attribute(:columns) || []
            fields = list_class.default_columns.collect{ |column| column.name } if fields.blank?

            available_columns = list_class.available_columns.inject({}) do |hash, column|
                hash[column.name] = column
                hash
            end

            @extended_columns = fields.inject([]) do |array, field|
                if available_columns[field.to_sym]
                    array << available_columns[field.to_sym]
                end
                array
            end
        end
    end

end

app/helpers/extended_fields_helper.rb
module ExtendedFieldsHelper

    def find_custom_field_template(custom_field)
        filename = custom_field.name.gsub(%r{[^a-z0-9_]+}i, '_').downcase
        filename.gsub!(%r{(^_+|_+$)}, '')

        format_extension = ''
        # Redmine 2.x.x
        if respond_to?(:formats)
            format_extension = ".#{formats.first}"
        # Redmine 1.x.x
        elsif request && request.respond_to?(:template_format)
            format_extension = ".#{request.template_format}"
        # Mailer
        elsif controller
            # Redmine 1.x.x
            if controller.respond_to?(:template)
                format_extension = ".#{controller.template.template_format}"
            # Redmine 2.x.x
            elsif controller.respond_to?(:lookup_context)
                format_extension = ".#{controller.lookup_context.formats.first}"
            end
        end

        unless filename.empty?
            self.view_paths.each do |load_path|
                if template = load_path["custom_values/#{custom_field.field_format}/_#{filename}#{format_extension}"]
                    return "custom_values/#{custom_field.field_format}/#{filename}"
                end
            end
        end

        self.view_paths.each do |load_path|
            if template = load_path["custom_values/common/_#{custom_field.field_format}#{format_extension}"]
                return "custom_values/common/#{custom_field.field_format}"
            end
        end

        nil
    end

    def find_custom_field_edit_template(custom_field)
        filename = custom_field.name.gsub(%r{[^a-z0-9_]+}i, '_').downcase
        filename.gsub!(%r{(^_+|_+$)}, '')

        unless filename.empty?
            self.view_paths.each do |load_path|
                if template = load_path["custom_edits/#{custom_field.field_format}/_#{filename}.html"]
                    return "custom_edits/#{custom_field.field_format}/#{filename}"
                end
            end
        end

        self.view_paths.each do |load_path|
            if template = load_path["custom_edits/common/_#{custom_field.field_format}.html"]
                return "custom_edits/common/#{custom_field.field_format}"
            end
        end

        nil
    end

    def custom_value_for_user(name, user = User.current)
        custom_field = CustomField.find_by_name_and_type(name, 'UserCustomField')
        if custom_field
            custom_value = user.custom_value_for(custom_field)
            if custom_value && !custom_value.value.blank?
                custom_value
            else
                nil
            end
        else
            nil
        end
    end

    def extended_column_content(column, object)
        value = column.value(object)

        case object
        when User
            case column.name
            when :login
                return (avatar(object, :size => 14) || '').html_safe + link_to(h(value), edit_user_path(object))
            when :mail
                return mail_to(h(value))
            when :status
                return h(l("status_" + %w(anonymous active registered locked)[value]))
            when :language
                language = valid_languages.detect{ |lang| lang.to_s == value }
                return h(ll(language.to_s, :general_lang_name))
            end
        when Project
            case column.name
            when :project
                return content_tag(:span, link_to_project_settings(object, { }, :title => object.short_description))
            when :description
                return textilizable(object.short_description, :project => object)
            when :created_on
                return format_date(value)
            when :homepage
                return link_to(h(value), value)
            when :active
                return checked_image(object.status == 1)
            end
        end

        case value
        when CustomValue
            return show_value(value)
        when User
            return link_to_user(value)
        when Project
            return link_to_project(value)
        when Version
            return link_to(h(value), :controller => 'versions', :action => 'show', :id => value)
        when Issue
            return link_to_issue(value, :subject => false)
        when Time
            return format_time(value)
        when Date
            return format_date(value)
        when TrueClass
            return checked_image(value)
        when FalseClass
            return nil
        else
            return h(value)
        end
    end

end

app/views/admin/projects.html.erb
<div class="contextual">
<%= link_to l(:label_project_new), {:controller => 'projects', :action => 'new'}, :class => 'icon icon-add' %>
</div>

<%= title l(:label_project_plural) %>

<%= form_tag({}, :onsubmit => 'selectAllOptions("selected_columns");', :method => :get, :id => 'project_list_form') do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>
<label for='status'><%= l(:field_status) %> :</label>
<%= select_tag 'status', project_status_options_for_select(@status), :class => "small", :onchange => "this.form.onsubmit(); this.form.submit(); return false;" %>
<label for='name'><%= l(:label_project) %>:</label>
<%= text_field_tag 'name', params[:name], :size => 30 %>
</fieldset>

<fieldset class="collapsible collapsed">
<legend onclick="toggleFieldset(this);"><%= l(:field_column_names) %></legend>
<div style="display: none;">
<%= render(:partial => 'custom_fields/columns', :locals => { :object => Project }) %>
</div>
</fieldset>

<%= hidden_field_tag('save', '') %>

<p class="buttons hide-when-print">
<% if defined? observe_field %>
<% project_list_form = "$('project_list_form')" %>
<% else %>
<% project_list_form = "$('#project_list_form')[0]" %>
<% end %>
<%= link_to_function(l(:button_apply), "var project_list_form = #{project_list_form}; project_list_form.onsubmit(); project_list_form.submit();", :class => 'icon icon-checked') %>
<%= link_to l(:button_clear), {:controller => 'admin', :action => 'projects'}, :class => 'icon icon-reload' %>
<%= link_to_function(l(:button_save), "var project_list_form = #{project_list_form}; project_list_form['save'].value = '1'; project_list_form.onsubmit(); project_list_form.submit();", :class => 'icon icon-save') %>
</p>

<% end %>

<div class="autoscroll">
<table class="list projects-listing">
  <thead><tr>
    <% @list_settings.columns.each do |column| %>
      <th><%= h(column.caption) %></th>
    <% end %>
  <th></th>
  </tr></thead>
  <tbody>
<% project_tree(@projects) do |project, level| %>
  <tr class="<%= cycle("odd", "even") %> <%= project.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    <% @list_settings.columns.each do |column| %>
      <td class="<%= h(column.css_classes) %>" align="<%= h(column.align) %>"><%= extended_column_content(column, project) %></td>
    <% end %>
  <td class="buttons">
    <%= link_to(l(:button_archive), { :controller => 'projects', :action => 'archive', :id => project, :status => params[:status] }, :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-lock') unless project.archived? %>
    <%= link_to(l(:button_unarchive), { :controller => 'projects', :action => 'unarchive', :id => project, :status => params[:status] }, :method => :post, :class => 'icon icon-unlock') if project.archived? && (project.parent.nil? || !project.parent.archived?) %>
    <%= link_to(l(:button_redirect), { :controller => 'removal', :action => 'edit', :id => project, :status => params[:status] }, :method => :post, :class => 'icon icon-move') if Redmine::Plugin.registered_plugins[:project_removal] && project.archived? %>
    <%= link_to(l(:button_copy), { :controller => 'projects', :action => 'copy', :id => project }, :class => 'icon icon-copy') %>
    <%= link_to(l(:button_delete), project_path(project), :method => :delete, :class => 'icon icon-del') %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<% html_title(l(:label_project_plural)) -%>

app/views/common/_calendar.html.erb
<table class="cal">
<thead>
<tr><th scope="col" title="<%= l(:label_week) %>" class="week-number"></th><% 7.times do |i| %><th scope="col"><%= day_name( (calendar.first_wday+i)%7 ) %></th><% end %></tr>
</thead>
<tbody>
<tr>
<% day = calendar.startdt
while day <= calendar.enddt %>
<%= ("<td class='week-number' title='#{ l(:label_week) }'>#{(day+(11-day.cwday)%7).cweek}</td>".html_safe) if day.cwday == calendar.first_wday %>
<td class="<%= day.month==calendar.month ? 'even' : 'odd' %><%= ' today' if Date.today == day %>">
<p class="day-num"><%= day.day %></p>
<% calendar.events_on(day).each do |i| %>
  <% if i.is_a? Issue %>
  <div class="<%= i.css_classes %> <%= 'starting' if day == i.start_date %> <%= 'ending' if day == i.due_date %> tooltip">
  <%= h("#{i.project} -") unless @project && @project == i.project %>
  <%= link_to_issue i, :truncate => 30 %>
  <span class="tip"><%= render_issue_tooltip i %></span>
  </div>
  <% elsif i.is_a? CustomValue %>
    <% if i.customized.visible? %>
      <% if i.customized.is_a? Issue %>
        <div class="<%= i.customized.css_classes %> tooltip">
          <span class="icon icon-time">
            <%= h(i.custom_field.name) %>:
            <%= h("#{i.customized.project} -") unless @project && @project == i.customized.project %>
            <%= link_to_issue(i.customized, :subject => false) %>
          </span>
          <span class="tip"><%= render_issue_tooltip(i.customized) %></span>
        </div>
      <% elsif i.customized.is_a? Project %>
        <span class="icon icon-time">
          <%= h(i.custom_field.name) %><% unless @project && @project == i.customized %>:
            <%= link_to_project(i.customized) %>
          <% end %>
        </span>
      <% else %>
        <span class="icon icon-time">
          <%= h(i.custom_field.name) %>:
          <%= h("#{i.customized.project} -") unless @project && @project == i.customized.project %>
          <%= link_to_version(i.customized) %>
        </span>
      <% end %>
    <% end %>
  <% else %>
  <span class="icon icon-package">
    <%= h("#{i.project} -") unless @project && @project == i.project %>
    <%= link_to_version i%>
  </span>
  <% end %>
<% end %>
</td>
<%= '</tr><tr>'.html_safe if day.cwday==calendar.last_wday and day!=calendar.enddt %>
<% day = day + 1
end %>
</tr>
</tbody>
</table>

app/views/custom_fields/_columns.html.erb
<table style="border-collapse: collapse; border: 0;">
  <tr>
    <td style="padding-left: 0;">
      <%= label_tag('available_columns', l(:description_available_columns)) %><br />
      <%= select_tag('available_columns',
                     options_for_select((object.available_columns - @list_settings.columns).collect{ |column| [ column.caption, column.name ]}.sort{ |a, b| a[0] <=> b[0] }),
                     :multiple => true, :size => 10, :style => 'width: 150px;',
                     :ondblclick => 'moveOptions(this.form.available_columns, this.form.selected_columns);') %>
    </td>
    <td align="center" valign="middle">
      <input type="button" value="&#8594;" onclick="moveOptions(this.form.available_columns, this.form.selected_columns);" /><br />
      <input type="button" value="&#8592;" onclick="moveOptions(this.form.selected_columns, this.form.available_columns);" />
    </td>
    <td>
      <%= label_tag('selected_columns', l(:description_selected_columns)) %><br />
      <%= select_tag('c[]',
                     options_for_select(@list_settings.columns.collect{ |column| [ column.caption, column.name ]}),
                     :id => 'selected_columns', :multiple => true, :size => 10, :style => 'width: 150px;',
                     :ondblclick => 'moveOptions(this.form.selected_columns, this.form.available_columns);') %>
    </td>
    <td align="center" valign="middle">
      <input type="button" value="&#8593;" onclick="moveOptionUp(this.form.selected_columns);" /><br />
      <input type="button" value="&#8595;" onclick="moveOptionDown(this.form.selected_columns);" />
    </td>
  </tr>
</table>

<% content_for :header_tags do %>
  <%= javascript_include_tag('select_list_move') %>
<% end %>

app/views/custom_fields/_extended.html.erb
<% projects = Project.all_public.active.sort_by(&:name).collect{ |project| [ project.name, project.id ] } %>

<% unless defined? observe_field %>

  <% if custom_field.field_format == 'project' %>

    <% blank_option = ''.html_safe %>
    <% if custom_field.is_required? %>
      <% unless custom_field.default_value.present? %>
        <% blank_option = content_tag(:option, "--- #{l(:actionview_instancetag_blank_option)} ---") %>
      <% end %>
    <% else %>
      <% blank_option = content_tag(:option) %>
    <% end %>

    <p>
      <%= form.select(:default_value, blank_option + options_for_select(projects, custom_field.default_value)) %>
    </p>

  <% end %>

<% end %>

<p><%= form.text_field(:hint, :size => 50) %></p>

<!-- Rails 3 + jQuery -->
<% unless defined? observe_field %>

  <% if custom_field.field_format == 'project' %>
    <script type="text/javascript">
    //<![CDATA[
      $('#custom_field_multiple').parent().hide();
      var default_value = $('#custom_field_default_value')
      if (default_value.prop('tagName') == 'INPUT') {
        default_value.parent().hide();
      }
    //]]>
    </script>
  <% end %>

  <% if Redmine::VERSION::MAJOR > 1 && Redmine::VERSION::MINOR > 1 && !defined?(ChiliProject) %>
    <%= javascript_tag('toggle_extended_field_format();') %>
  <% end %>

<!-- Rails 2 + prototype -->
<% else %>
  <%= javascript_tag('toggle_extended_field_format();') %>
<% end %>

<% content_for :header_tags do %>

  <script type="text/javascript">
  //<![CDATA[
    var projects = <%= projects.to_json.html_safe %>;
    var actionview_instancetag_blank_option = '<%= "--- #{l(:actionview_instancetag_blank_option)} ---" %>';
  //]]>
  </script>

  <!-- Rails 2 + prototype -->
  <% if defined? observe_field %>
    <%= javascript_include_tag('extended_prototype', :plugin => 'extended_fields') %>

    <script type="text/javascript">
    //<![CDATA[
      Event.observe(window, 'load', function() {
        Event.observe('custom_field_field_format', 'change', toggle_extended_field_format);
        toggle_extended_field_format();
      });
    //]]>
    </script>

  <!-- Rails 3 + jQuery -->
  <% else %>
    <%= javascript_include_tag('extended_jquery', :plugin => 'extended_fields') %>
  <% end %>

<% end %>

app/views/custom_fields/_options.html.erb
<% case custom_field.class.name
   when 'UserCustomField' %>
  <p><%= form.check_box(:significant, :label => l(:label_on_registration)) %></p>
<% when 'VersionCustomField' %>
  <p><%= form.check_box(:significant, :label => l(:label_shown_on_project_page)) %></p>
<% end %>

app/views/custom_fields/formats/_project.html.erb
<p><%= edit_tag_style_tag f %></p>

app/views/custom_values/common/_link.html.erb
<% link = (custom_field.value =~ %r{^https?://}) ? custom_field.value : "http://#{custom_field.value}" %>
<%= link_to(h(custom_field.value), link, :class => 'external') %>

app/views/custom_values/common/_link.text.erb
<%= (custom_field.value =~ %r{^https?://}) ? custom_field.value : "http://#{custom_field.value}" %>

app/views/custom_values/common/_project.html.erb
<% project = Project.find_by_id(custom_field.value) %>
<%= link_to_project(project) if project %>

app/views/custom_values/common/_project.text.erb
<% project = Project.find_by_id(custom_field.value) %><%= project.name if project %>

app/views/custom_values/common/_wiki.html.erb
<div class="wiki">
  <%= textilizable(custom_field.value) %>
</div>

app/views/users/index.html.erb
<div class="contextual">
<%= link_to l(:label_user_new), new_user_path, :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_user_plural)%></h2>

<%= form_tag(users_path, :onsubmit => 'selectAllOptions("selected_columns");', :method => :get, :id => 'user_list_form') do %>
<fieldset><legend><%= l(:label_filter_plural) %></legend>
<label for='status'><%= l(:field_status) %>:</label>
<%= select_tag 'status', users_status_options_for_select(@status), :class => "small", :onchange => "this.form.onsubmit(); this.form.submit(); return false;"  %>

<% if @groups.present? %>
<label for='group_id'><%= l(:label_group) %>:</label>
<%= select_tag 'group_id', content_tag('option') + options_from_collection_for_select(@groups, :id, :name, params[:group_id].to_i), :onchange => "this.form.onsubmit(); this.form.submit(); return false;" %>
<% end %>

<label for='name'><%= l(:label_user) %>:</label>
<%= text_field_tag 'name', params[:name], :size => 30 %>
</fieldset>

<fieldset class="collapsible collapsed">
<legend onclick="toggleFieldset(this);"><%= l(:field_column_names) %></legend>
<div style="display: none;">
<%= render(:partial => 'custom_fields/columns', :locals => { :object => User }) %>
</div>
</fieldset>

<%= hidden_field_tag('save', '') %>

<p class="buttons hide-when-print">
<% if defined? observe_field %>
<% user_list_form = "$('user_list_form')" %>
<% else %>
<% user_list_form = "$('#user_list_form')[0]" %>
<% end %>
<%= link_to_function(l(:button_apply), "var user_list_form = #{user_list_form}; user_list_form.onsubmit(); user_list_form.submit();", :class => 'icon icon-checked') %>
<%= link_to l(:button_clear), users_path, :class => 'icon icon-reload' %>
<%= link_to_function(l(:button_save), "var user_list_form = #{user_list_form}; user_list_form['save'].value = '1'; user_list_form.onsubmit(); user_list_form.submit();", :class => 'icon icon-save') %>
</p>

<% end %>

<div class="autoscroll">
<table class="list users-listing">
  <thead><tr>
      <% @list_settings.columns.each do |column| %>
        <% if %w(login firstname lastname mail admin created_on last_login_on).include?(column.name.to_s) %>
          <%= sort_header_tag(column.name.to_s, :caption => column.caption) %>
        <% else %>
          <th><%= h(column.caption) %></th>
        <% end %>
      <% end %>
    <th></th>
  </tr></thead>
  <tbody>
<% for user in @users -%>
  <tr class="<%= user.css_classes %> <%= cycle("odd", "even") %>">
    <% @list_settings.columns.each do |column| %>
      <td class="<%= h(column.css_classes) %>" align="<%= h(column.align) %>"><%= extended_column_content(column, user) %></td>
    <% end %>
    <td class="buttons">
      <%= change_status_link(user) %>
      <%= delete_link user_path(user, :back_url => users_path(params)) unless User.current == user %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<p class="pagination"><%= pagination_links_full @user_pages, @user_count %></p>

<% html_title(l(:label_user_plural)) -%>